package ru.practicum.shareit.shareit.exception;

import org.junit.jupiter.api.Test;

class ErrorResponseTest {

    @Test
    void getError() {

    }
}